### ISSUE TITLE
PDF file

### ISSUE THREAD

**Issue by ghost** [paulvee/Dynamic-DC-Load#1]
Can you upload the schematic PDF file?

**Comment by paulvee** [comment]
It is already there, as a PNG formatted file

**Comment by ghost** [comment]
Can't see the components clearly and identify the components can you please send PDF

**Comment by paulvee** [comment]
OK, the "please" helped and I learned something new.
I didn't know you could create a pdf from KiCad. I do now. It's uploaded.
This will hopefully help you.
